on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  build:
    uses: Hanawa02/money-tracker-frontend/.github/workflows/build.yml@main
    secrets: inherit

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔨 Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Download Dist Folder
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: ./dist/
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_PROD }}
          username: ${{ secrets.FTP_USERNAME_PROD }}
          password: ${{ secrets.FTP_PASSWORD_PROD }}
          local-dir: ./dist/
